### PR TITLE
replace references to Astroconda with `stenv`

### PR DESCRIPTION
**Pull request by zacharyburnett**
[SCSB-44](https://jira.stsci.edu/browse/SCSB-44)

`stenv`, as a repository, builds and tests environments based on inter-package requirements

### CODE REVIEW

**Comment by zacharyburnett** [comment]
@bourque @shanosborne

**Comment by bourque** [comment]
@zacharyburnett Uhh yeah, we don't work here anymore.  Good luck!

**Comment by zacharyburnett** [comment]
> @zacharyburnett Uhh yeah, we don't work here anymore. Good luck!

oh ok, thanks for replying!

**Comment by bourque** [comment]
@zacharyburnett I'm not sure if anyone is in charge of this repo anymore -- a good person to ask might be Jeff Valenti.

**Comment by shanosborne** [comment]
I believe @BradleySappington and @mfixstsci have taken over this project. Hopefully they can help

**Comment by zacharyburnett** [comment]
> I believe @BradleySappington and @mfixstsci have taken over this project. Hopefully they can help

Thanks!

**Comment by mfixstsci** [comment]
@zacharyburnett -- @shanosborne is correct, feel free to ping @BradleySappington and myself from now on.

Hey 👋 @bourque and @shanosborne hope all is well and thanks for responding!

**Pull request merged**
